apiVersion: ec2.aws.crossplane.io/v1alpha1
kind: Instance
metadata:
  name: cool-new-instance1
spec:
  forProvider:
    region: us-east-1
    imageId: ami-0dc2d3e4c0f9ebd18
    blockDeviceMappings:
      - deviceName: /dev/sdx
        ebs:
          volumeSize: 100
    securityGroupRefs:
      - name: cool-new-instances-sg
    subnetIdRef:
      name: cool-new-subnet1
  providerConfigRef:
    name: localstack